# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  matcrmapi:
    image: matcrmapi
    build:
      context: .
      # dockerfile: api-crm/matcrm.api/Dockerfile
    ports:
      - 5100:5100
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
  # apiforms:
  #   image: apiforms
  #   build:
  #     context: .
  #     dockerfile: api-forms/api-forms.api/Dockerfile
  #   ports:
  #     - 5200:5200
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   volumes:
  #     - ~/.vsdbg:c:\remote_debugger:rw 
  # appcrm:
  #   image: appcrm
  #   build:
  #     context: .
  #     dockerfile: app-crm/Dockerfile
  #   ports:
  #     - 4100:80   
  # appmail:
  #   image: appmail
  #   build:
  #     context: .
  #     dockerfile: app-mail/Dockerfile
  #   ports:
  #     - 4200:80
  # appforms:
  #   image: appforms
  #   build:
  #     context: .
  #     dockerfile: app-forms/Dockerfile
  #   ports:
  #     - 4300:80                
